# Generated by Django 2.1.4 on 2019-02-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('thinger_username', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=1000)),
                ('is_connected', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resources_name', models.CharField(max_length=100)),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='THINGER_API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thinger_api_name', models.CharField(max_length=100)),
            ],
        ),
    ]
