# Generated by Django 2.1.4 on 2019-02-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vinus', '0002_auto_20190220_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='user',
            new_name='userr',
        ),
    ]
