# Generated by Django 2.1.4 on 2019-02-23 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vinus', '0003_auto_20190223_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='userr',
            new_name='user',
        ),
    ]
