# Generated by Django 2.1 on 2019-02-23 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vinus', '0005_auto_20190223_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='userr',
            new_name='user',
        ),
    ]
