# Generated by Django 2.1.4 on 2019-02-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vinus', '0007_device_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='slug',
        ),
    ]
