# Generated by Django 2.1.4 on 2019-02-27 15:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Vinus', '0008_remove_device_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('device_name', 'user')},
        ),
    ]
