# Generated by Django 2.1.4 on 2019-02-27 22:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vinus', '0009_auto_20190227_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='type',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(4)]),
        ),
    ]
