# Generated by Django 2.1.4 on 2019-02-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vinus', '0011_auto_20190227_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='type',
            field=models.IntegerField(choices=[(1, 'Output Resources'), (2, 'Input Resources'), (3, 'Input/Output Resources'), (4, 'Resources without parameters')], default=1),
        ),
    ]
