# Generated by Django 2.1.4 on 2019-02-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vinus', '0012_auto_20190227_2302'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='thinger_api',
            unique_together={('device', 'thinger_api_name')},
        ),
    ]
