# Generated by Django 2.1 on 2019-03-01 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vinus', '0013_auto_20190228_0959'),
        ('Vinus', '0013_auto_20190228_1019'),
    ]

    operations = [
    ]
