# Generated by Django 2.1.4 on 2019-03-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vinus', '0013_auto_20190228_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='data_type',
            field=models.IntegerField(choices=[(1, 'Integer'), (2, 'Double'), (3, 'Bool'), (4, 'Other')], default=1),
        ),
    ]
