# Generated by Django 2.1 on 2019-03-15 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vinus', '0014_merge_20190301_2045'),
        ('Vinus', '0014_resources_data_type'),
    ]

    operations = [
    ]
