# Generated by Django 2.1.4 on 2019-03-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vinus', '0016_auto_20190318_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thinger_api',
            name='type',
            field=models.IntegerField(choices=[(1, 'Output APIs'), (2, 'Input APIs'), (3, 'Input/Output APIs'), (4, 'APIs without parameters')], default=1),
        ),
    ]
